#!/usr/bin/env python3
"""Generate the public-facing STATUS.md from a live Sentinel workspace.

Reads the workspace's shadow + watch state files and produces a
markdown document suitable for posting to a public GitHub Gist.

Usage:
    python3 generate_status.py [<workspace>] [<output>]

Default workspace: /root/audit_runs/percolator-live
Default output:    /tmp/STATUS.md
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def tail_lines(path: Path, n: int) -> list[str]:
    if not path.exists():
        return []
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            return f.readlines()[-n:]
    except OSError:
        return []


def tmux_session_alive(name: str) -> bool:
    try:
        result = subprocess.run(
            ["tmux", "has-session", "-t", name],
            capture_output=True, timeout=5,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def main() -> None:
    workspace = Path(sys.argv[1] if len(sys.argv) > 1 else "/root/audit_runs/percolator-live")
    output = Path(sys.argv[2] if len(sys.argv) > 2 else "/tmp/STATUS.md")

    config = read_json(workspace / "workspace.json")
    shadow_state = read_json(workspace / "shadow" / "state.json")
    watch_state = read_json(workspace / "watch" / "state.json")
    alerts_path = workspace / "shadow" / "alerts.jsonl"
    alert_count = sum(1 for _ in alerts_path.open()) if alerts_path.exists() else 0
    recent_alerts = tail_lines(alerts_path, 10)

    shadow_alive = tmux_session_alive("sentinel-shadow")
    watch_alive = tmux_session_alive("sentinel-watch")

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    lines: list[str] = []
    lines.append("# Sentinel — Live operational status")
    lines.append("")
    lines.append("**Pipeline:** [Sentinel audit-pipeline](https://github.com/Copenhagen0x/audit-pipeline-cli)")
    lines.append("**Methodology:** [solana-audit-pipeline](https://github.com/Copenhagen0x/solana-audit-pipeline)")
    lines.append("")
    lines.append(f"**Target:** {config.get('target_name', 'unknown')}")
    lines.append(f"**Mainnet program:** `6qWZvUtfyShbxTQkwjCayk3LuGqTGJwBo2QfkePK5jdJ`")
    lines.append(f"**Last refresh:** {now}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Daemons")
    lines.append("")
    lines.append("| Daemon | Status | Polling cadence |")
    lines.append("|---|---|---|")
    lines.append(f"| sentinel-shadow | {'RUNNING' if shadow_alive else 'DOWN'} | mainnet RPC every 60s |")
    lines.append(f"| sentinel-watch | {'RUNNING' if watch_alive else 'DOWN'} | GitHub upstream every 300s |")
    lines.append("")

    lines.append("## Source-code watch")
    lines.append("")
    lines.append("Pinned SHAs (auto-updated when new commits land upstream):")
    lines.append("")
    lines.append("```json")
    pinned = {
        "engine": config.get("engine", {}),
        "wrapper": config.get("wrapper", {}),
        "last_watch_update": config.get("last_watch_update"),
    }
    lines.append(json.dumps(pinned, indent=2))
    lines.append("```")
    lines.append("")
    if watch_state:
        lines.append("Watch state:")
        lines.append("```json")
        lines.append(json.dumps(watch_state, indent=2))
        lines.append("```")
        lines.append("")

    lines.append("## Mainnet shadow")
    lines.append("")
    if shadow_state:
        lines.append("Most recent poll snapshot:")
        lines.append("```json")
        lines.append(json.dumps(shadow_state, indent=2))
        lines.append("```")
        lines.append("")
        last_sig = shadow_state.get("last_seen_sig")
        if last_sig:
            lines.append(
                f"Verify on-chain: https://explorer.solana.com/tx/{last_sig}"
            )
            lines.append("")
    else:
        lines.append("_Shadow not yet polled (or state file missing)._")
        lines.append("")

    lines.append("## Alerts")
    lines.append("")
    lines.append(f"**Total alerts logged:** {alert_count}")
    lines.append("")
    if alert_count > 0:
        lines.append("Most recent (up to 10):")
        lines.append("```json")
        for raw in recent_alerts:
            lines.append(raw.rstrip())
        lines.append("```")
    else:
        lines.append("_No alerts in window — pipeline polling normally._")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Auto-generated by the Sentinel pipeline. Updates hourly.*")
    lines.append("")
    lines.append(
        "*Verification: the `last_seen_sig` above is a real Solana mainnet "
        "transaction signature. Look it up on any block explorer to confirm "
        "this pipeline is polling live mainnet, not faking data.*"
    )

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output} ({len(lines)} lines, alerts={alert_count})")


if __name__ == "__main__":
    main()
