"""`audit-pipeline init` — scaffold a new audit workspace.

Creates the directory structure, clones the target repos at pinned SHAs,
and writes the workspace config file.
"""

import json
import shutil
import subprocess
from pathlib import Path

import click
from rich.console import Console
from rich.tree import Tree

console = Console()


WORKSPACE_LAYOUT = [
    "target/engine",
    "target/wrapper",
    "recon",
    "tests/engine",
    "tests/wrapper",
    "results",
    "docs",
    "disclosure",
]


@click.command(name="init")
@click.option(
    "--engine-repo",
    required=True,
    help="Engine repository URL (e.g. https://github.com/aeyakovenko/percolator)",
)
@click.option(
    "--engine-sha",
    required=True,
    help="Engine SHA to pin (e.g. 5940285)",
)
@click.option(
    "--wrapper-repo",
    required=True,
    help="Wrapper repository URL (e.g. https://github.com/aeyakovenko/percolator-prog)",
)
@click.option(
    "--wrapper-sha",
    required=True,
    help="Wrapper SHA to pin (e.g. c447686)",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(file_okay=False, path_type=Path),
    required=True,
    help="Path to create the workspace at",
)
@click.option(
    "--target-name",
    default=None,
    help="Short name for the target (defaults to engine repo name)",
)
@click.option(
    "--clone/--no-clone",
    default=True,
    show_default=True,
    help="Clone the target repos into target/ (skip if you'll sync via VPS only)",
)
def init_cmd(
    engine_repo: str,
    engine_sha: str,
    wrapper_repo: str,
    wrapper_sha: str,
    output: Path,
    target_name: str | None,
    clone: bool,
) -> None:
    """Scaffold a new audit workspace at OUTPUT.

    Creates the directory structure, optionally clones the target repos,
    and writes a workspace config file.
    """
    if output.exists() and any(output.iterdir()):
        raise click.ClickException(
            f"Output path {output} exists and is not empty. Refusing to overwrite. "
            f"Pass --output to a fresh path."
        )

    output.mkdir(parents=True, exist_ok=True)

    # Layout
    console.print(f"[cyan]Creating workspace layout at {output}[/cyan]")
    for subpath in WORKSPACE_LAYOUT:
        (output / subpath).mkdir(parents=True, exist_ok=True)

    # Clone target repos if requested
    if clone:
        console.print(f"[cyan]Cloning {engine_repo} @ {engine_sha}[/cyan]")
        _clone_at_sha(engine_repo, engine_sha, output / "target/engine")

        console.print(f"[cyan]Cloning {wrapper_repo} @ {wrapper_sha}[/cyan]")
        _clone_at_sha(wrapper_repo, wrapper_sha, output / "target/wrapper")

    # Workspace config
    target = target_name or _repo_name_from_url(engine_repo)
    config = {
        "target_name": target,
        "engine": {"repo": engine_repo, "sha": engine_sha, "local": "target/engine"},
        "wrapper": {"repo": wrapper_repo, "sha": wrapper_sha, "local": "target/wrapper"},
        "vps": {"host": None, "ssh_key": None},  # filled in by `provision-vps`
        "audit_pipeline_version": "0.1.0",
    }
    config_path = output / "workspace.json"
    config_path.write_text(json.dumps(config, indent=2))
    console.print(f"[green]Wrote workspace config to {config_path}[/green]")

    # Stub README
    readme = output / "README.md"
    if not readme.exists():
        readme.write_text(f"# {target} audit workspace\n\nGenerated by `audit-pipeline init`.\n\nNext steps:\n\n1. `audit-pipeline provision-vps --host <vps> --ssh-key <key>`\n2. `audit-pipeline sync --host <vps> --ssh-key <key>`\n3. `audit-pipeline recon --hypotheses hypotheses.yaml`\n4. ...\n\nSee https://github.com/Copenhagen0x/solana-audit-pipeline for methodology.\n")

    # Print summary tree
    console.print()
    tree = Tree(f"[bold]{output.resolve()}[/bold]")
    for subpath in WORKSPACE_LAYOUT:
        tree.add(subpath)
    tree.add("workspace.json")
    tree.add("README.md")
    console.print(tree)

    console.print()
    console.print(f"[bold green]Workspace ready.[/bold green]")
    console.print(f"  Next step: [cyan]cd {output} && audit-pipeline provision-vps --host <vps> --ssh-key <key>[/cyan]")


def _clone_at_sha(repo_url: str, sha: str, dest: Path) -> None:
    """Shallow clone the repo, then checkout the specific SHA."""
    if dest.exists() and (dest / ".git").exists():
        # Already cloned; just checkout
        subprocess.run(["git", "fetch", "origin"], cwd=dest, check=True)
        subprocess.run(["git", "checkout", sha], cwd=dest, check=True)
    else:
        if dest.exists():
            shutil.rmtree(dest)
        subprocess.run(
            ["git", "clone", repo_url, str(dest)],
            check=True,
        )
        subprocess.run(["git", "checkout", sha], cwd=dest, check=True)


def _repo_name_from_url(url: str) -> str:
    """Extract repo name from a Git URL."""
    return url.rstrip("/").split("/")[-1].removesuffix(".git")
